In [1]:
import pandas as pd
import requests

In [5]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=6b4bf614172e96c377e0fc2b299dc5eb&language=en-US&page=1')

In [16]:
temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'vote_average', 'vote_count', 'release_date', 'original_language']]

In [14]:
df.head(10)

,id,title,vote_average,vote_count,release_date,original_language
0,1007757,Swapped,8.917,1892,2026-05-01,en
1,278,The Shawshank Redemption,8.724,30715,1994-09-23,en
2,936075,Michael,8.706,3355,2026-04-22,en
3,238,The Godfather,8.687,23128,1972-03-14,en
4,687163,Project Hail Mary,8.675,5821,2026-03-15,en
5,240,The Godfather Part II,8.571,14020,1974-12-20,en
6,424,Schindler's List,8.570,17578,1993-12-15,en
7,389,12 Angry Men,8.565,10097,1957-04-10,en
8,1330021,Remarkably Bright Creatures,8.553,703,2026-05-07,en
9,1383731,Protector,8.544,410,2026-02-20,en

In [15]:
df = pd.DataFrame()

In [18]:
import time

for i in range(1, 550):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=6b4bf614172e96c377e0fc2b299dc5eb&language=en-US&page=' + str(i))
    if 'results' not in response.json():
        print(f"Error on page {i}: {response.json()}")
        break

    temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'vote_average', 'vote_count', 'release_date', 'original_language']]
    df = pd.concat([df, temp_df], ignore_index=True)

    time.sleep(1)

Error on page 501: {'success': False, 'status_code': 22, 'status_message': 'Invalid page: Pages start at 1 and max at 500. They are expected to be an integer.'}

In [19]:
df.shape

(20000, 6)

In [20]:
df

,id,title,vote_average,vote_count,release_date,original_language
0,1007757,Swapped,8.917,1892,2026-05-01,en
1,278,The Shawshank Redemption,8.724,30715,1994-09-23,en
2,936075,Michael,8.706,3355,2026-04-22,en
3,238,The Godfather,8.687,23128,1972-03-14,en
4,687163,Project Hail Mary,8.675,5821,2026-03-15,en
...,...,...,...,...,...,...
19995,12521,Shocker,5.582,465,1989-03-23,en
19996,1010826,Killer Book Club,5.581,315,2023-08-25,es
19997,12618,Random Hearts,5.581,426,1999-10-08,en
19998,241257,Regression,5.580,1895,2015-10-01,en
19999,14435,My Bloody Valentine,5.580,1323,2009-01-16,en

In [21]:
# Check for duplicates
df.duplicated(subset=['id']).sum()

# If there are duplicates, remove them
df = df.drop_duplicates(subset=['id'], keep='first')

# Check shape again
df.shape

(9998, 6)

In [22]:
df.to_csv('top_rated_movies.csv', index=False)