### Feature scaling is a technique used to standardize the independent features present in the dataset

#### Types of feature scaling
* Standardization
* Normalization

# Standardization (Z-score normalization)

<p> To scale the values accordingly using standardization, we do: xi' = (xi-mean)/sigma (STD)

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df = df[['Age', 'Fare', 'Survived']]

In [5]:
df.sample(5)

      Age     Fare  Survived
362  45.0  14.4542         0
472  33.0  27.7500         1
648   NaN   7.5500         0
167  45.0  27.9000         0
83   28.0  47.1000         0

# Train Test Split

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['Age', 'Fare']], df['Survived'], test_size=0.2, random_state=0)

X_train.shape, X_test.shape

((712, 2), (179, 2))

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
scaler.mean_, scaler.scale_

(array([29.74518389, 31.86294986]), array([14.60623921, 50.10008981]))

In [13]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [14]:
X_train_scaled

          Age      Fare
0         NaN -0.331679
1    0.085910 -0.426405
2    0.085910  0.102620
3   -0.667193 -0.555896
4   -0.598729 -0.491276
..        ...       ...
707  0.633621  1.023857
708 -0.735657 -0.479216
709       NaN -0.481629
710  0.428229 -0.288681
711  2.071362  0.142456

[712 rows x 2 columns]

In [15]:
np.round(X_train_scaled.describe(), 1)

         Age   Fare
count  571.0  712.0
mean     0.0    0.0
std      1.0    1.0
min     -2.0   -0.6
25%     -0.6   -0.5
50%     -0.1   -0.3
75%      0.6   -0.0
max      3.4    9.6

#### When to use standardization?
* K-means
* KNN
* PCA
* Artificial Neural Network
* Gradient Descent