# Web Scraping

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
webpage = requests.get('https://quotes.toscrape.com/page/1/').text

In [3]:
soup = BeautifulSoup(webpage, 'lxml')

In [4]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Quotes to Scrape
  </title>
  <link href="/static/bootstrap.min.css" rel="stylesheet"/>
  <link href="/static/main.css" rel="stylesheet"/>
 </head>
 <body>
  <div class="container">
   <div class="row header-box">
    <div class="col-md-8">
     <h1>
      <a href="/" style="text-decoration: none">
       Quotes to Scrape
      </a>
     </h1>
    </div>
    <div class="col-md-4">
     <p>
      <a href="/login">
       Login
      </a>
     </p>
    </div>
   </div>
   <div class="row">
    <div class="col-md-8">
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
       <a class="tag" href="/tag/change/page/1/">
        change
       </a>
       <a class="tag" href="/tag/deep-thoughts/page/1/">
        deep-thoughts
       </a>
       <a class="tag" href="/tag/thinking/page/1/">
        thinking
       </a>
       <a class="tag" href="/tag/world/page/1/">
        world
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “It is our choices, Harry, that show what we truly are, far more than our abilities.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        J.K. Rowling
       </small>
       <a href="/author/J-K-Rowling">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
       <a class="tag" href="/tag/abilities/page/1/">
        abilities
       </a>
       <a class="tag" href="/tag/choices/page/1/">
        choices
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
       <a class="tag" href="/tag/life/page/1/">
        life
       </a>
       <a class="tag" href="/tag/live/page/1/">
        live
       </a>
       <a class="tag" href="/tag/miracle/page/1/">
        miracle
       </a>
       <a class="tag" href="/tag/miracles/page/1/">
        miracles
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Jane Austen
       </small>
       <a href="/author/Jane-Austen">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
       <a class="tag" href="/tag/aliteracy/page/1/">
        aliteracy
       </a>
       <a class="tag" href="/tag/books/page/1/">
        books
       </a>
       <a class="tag" href="/tag/classic/page/1/">
        classic
       </a>
       <a class="tag" href="/tag/humor/page/1/">
        humor
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Marilyn Monroe
       </small>
       <a href="/author/Marilyn-Monroe">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
       <a class="tag" href="/tag/be-yourself/page/1/">
        be-yourself
       </a>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “Try not to become a man of success. Rather become a man of value.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
       <a class="tag" href="/tag/adulthood/page/1/">
        adulthood
       </a>
       <a class="tag" href="/tag/success/page/1/">
        success
       </a>
       <a class="tag" href="/tag/value/page/1/">
        value
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “It is better to be hated for what you are than to be loved for what you are not.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        André Gide
       </small>
       <a href="/author/Andre-Gide">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="life,love" itemprop="keywords"/>
       <a class="tag" href="/tag/life/page/1/">
        life
       </a>
       <a class="tag" href="/tag/love/page/1/">
        love
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “I have not failed. I've just found 10,000 ways that won't work.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Thomas A. Edison
       </small>
       <a href="/author/Thomas-A-Edison">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
       <a class="tag" href="/tag/edison/page/1/">
        edison
       </a>
       <a class="tag" href="/tag/failure/page/1/">
        failure
       </a>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
       <a class="tag" href="/tag/paraphrased/page/1/">
        paraphrased
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “A woman is like a tea bag; you never know how strong it is until it's in hot water.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Eleanor Roosevelt
       </small>
       <a href="/author/Eleanor-Roosevelt">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
       <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">
        misattributed-eleanor-roosevelt
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “A day without sunshine is like, you know, night.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Steve Martin
       </small>
       <a href="/author/Steve-Martin">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
       <a class="tag" href="/tag/humor/page/1/">
        humor
       </a>
       <a class="tag" href="/tag/obvious/page/1/">
        obvious
       </a>
       <a class="tag" href="/tag/simile/page/1/">
        simile
       </a>
      </div>
     </div>
     <nav>
      <ul class="pager">
       <li class="next">
        <a href="/page/2/">
         Next
         <span aria-hidden="true">
          →
         </span>
        </a>
       </li>
      </ul>
     </nav>
    </div>
    <div class="col-md-4 tags-box">
     <h2>
      Top Ten tags
     </h2>
     <span class="tag-item">
      <a class="tag" href="/tag/love/" style="font-size: 28px">
       love
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/inspirational/" style="font-size: 26px">
       inspirational
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/life/" style="font-size: 26px">
       life
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/humor/" style="font-size: 24px">
       humor
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/books/" style="font-size: 22px">
       books
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/reading/" style="font-size: 14px">
       reading
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/friendship/" style="font-size: 10px">
       friendship
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/friends/" style="font-size: 8px">
       friends
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/truth/" style="font-size: 8px">
       truth
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/simile/" style="font-size: 6px">
       simile
      </a>
     </span>
    </div>
   </div>
  </div>
  <footer class="footer">
   <div class="container">
    <p class="text-muted">
     Quotes by:
     <a href="https://www.goodreads.com/quotes">
      GoodReads.com
     </a>
    </p>
    <p class="copyright">
     Made with
     <span class="zyte">
      ❤
     </span>
     by
     <a class="zyte" href="https://www.zyte.com">
      Zyte
     </a>
    </p>
   </div>
  </footer>
 </body>
</html>

In [5]:
soup.find_all('h1')[0].text

'\nQuotes to Scrape\n'

In [6]:
for i in soup.find_all('span', class_='text'):
    print(i.text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
“Try not to become a man of success. Rather become a man of value.”
“It is better to be hated for what you are than to be loved for what you are not.”
“I have not failed. I've just found 10,000 ways that won't work.”
“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
“A day without sunshine is like, you know, night.”

In [7]:
for i in soup.find_all('small', class_='author'):
    print(i.text)

Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe
Albert Einstein
André Gide
Thomas A. Edison
Eleanor Roosevelt
Steve Martin

In [8]:
for i in soup.find_all('a', class_='tag'):
    print(i.text)

change
deep-thoughts
thinking
world
abilities
choices
inspirational
life
live
miracle
miracles
aliteracy
books
classic
humor
be-yourself
inspirational
adulthood
success
value
life
love
edison
failure
inspirational
paraphrased
misattributed-eleanor-roosevelt
humor
obvious
simile
love
inspirational
life
humor
books
reading
friendship
friends
truth
simile

In [9]:
df = pd.DataFrame(columns=['Quote', 'Author', 'Tags'])

quotes = soup.find_all('div', class_='quote')

for quote in quotes:
    text = quote.find('span', class_='text').text
    author = quote.find('small', class_='author').text
    tags = [tag.text for tag in quote.find_all('a', class_='tag')]

    df = pd.concat([df, pd.DataFrame({'Quote': [text], 'Author': [author], 'Tags': [tags]})], ignore_index=True)

df

,Quote,Author,Tags
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]"
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]"
5,“Try not to become a man of success. Rather be...,Albert Einstein,"[adulthood, success, value]"
6,“It is better to be hated for what you are tha...,André Gide,"[life, love]"
7,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"[edison, failure, inspirational, paraphrased]"
8,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,[misattributed-eleanor-roosevelt]
9,"“A day without sunshine is like, you know, nig...",Steve Martin,"[humor, obvious, simile]"

In [21]:
final = pd.DataFrame(columns=['Quote', 'Author First Name', 'Author Last Name', 'Tags'])

for j in range(1, 11):
    webpage = requests.get(f'https://quotes.toscrape.com/page/{j}/').text
    soup = BeautifulSoup(webpage, 'lxml')

    quotes = soup.find_all('div', class_='quote')

    for quote in quotes:
        text = quote.find('span', class_='text').text
        authorFirst = quote.find('small', class_='author').text.split()[0]
        authorLast = quote.find('small', class_='author').text.split()[-1]
        tags = [tag.text for tag in quote.find_all('a', class_='tag')]
        final = pd.concat([final, pd.DataFrame({'Quote': [text], 'Author First Name': [authorFirst], 'Author Last Name': [authorLast], 'Tags': [tags]})], ignore_index=True)

final

,Quote,Author First Name,Author Last Name,Tags
0,“The world as we have created it is a process ...,Albert,Einstein,"[change, deep-thoughts, thinking, world]"
1,"“It is our choices, Harry, that show what we t...",J.K.,Rowling,"[abilities, choices]"
2,“There are only two ways to live your life. On...,Albert,Einstein,"[inspirational, life, live, miracle, miracles]"
3,"“The person, be it gentleman or lady, who has ...",Jane,Austen,"[aliteracy, books, classic, humor]"
4,"“Imperfection is beauty, madness is genius and...",Marilyn,Monroe,"[be-yourself, inspirational]"
...,...,...,...,...
95,“You never really understand a person until yo...,Harper,Lee,[better-life-empathy]
96,“You have to write the book that wants to be w...,Madeleine,L'Engle,"[books, children, difficult, grown-ups, write,..."
97,“Never tell the truth to people who are not wo...,Mark,Twain,[truth]
98,"“A person's a person, no matter how small.”",Dr.,Seuss,[inspirational]
99,“... a mind needs books as a sword needs a whe...,George,Martin,"[books, mind]"

In [11]:
filtered = df[df['Tags'].apply(lambda x: 'be-yourself' in x)]
filtered

,Quote,Author,Tags,Author First Name,Author Last Name
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]",NaN,NaN
14,"“Imperfection is beauty, madness is genius and...",NaN,"[be-yourself, inspirational]",Marilyn,Monroe

In [12]:
filtered = df[df['Tags'].apply(lambda x: 'live' in x)]
len(filtered)
filtered

,Quote,Author,Tags,Author First Name,Author Last Name
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]",NaN,NaN
12,“There are only two ways to live your life. On...,NaN,"[inspirational, life, live, miracle, miracles]",Albert,Einstein

In [13]:
filtered = df[df['Author'] == 'Mark Twain']
filtered

Empty DataFrame
Columns: [Quote, Author, Tags, Author First Name, Author Last Name]
Index: []

In [14]:
len(filtered)

0

In [15]:
print(df.sort_values(by='Author', ascending=True))

                                                 Quote             Author  \
0    “The world as we have created it is a process ...    Albert Einstein
2    “There are only two ways to live your life. On...    Albert Einstein
5    “Try not to become a man of success. Rather be...    Albert Einstein
6    “It is better to be hated for what you are tha...         André Gide
8    “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
..                                                 ...                ...
105  “You never really understand a person until yo...                NaN
106  “You have to write the book that wants to be w...                NaN
107  “Never tell the truth to people who are not wo...                NaN
108        “A person's a person, no matter how small.”                NaN
109  “... a mind needs books as a sword needs a whe...                NaN

                                                  Tags Author First Name  \
0             [change, deep-thoughts, thinking, world]               NaN
2       [inspirational, life, live, miracle, miracles]               NaN
5                          [adulthood, success, value]               NaN
6                                         [life, love]               NaN
8                    [misattributed-eleanor-roosevelt]               NaN
..                                                 ...               ...
105                              [better-life-empathy]            Harper
106  [books, children, difficult, grown-ups, write,...         Madeleine
107                                            [truth]              Mark
108                                    [inspirational]               Dr.
109                                      [books, mind]            George

    Author Last Name
0                NaN
2                NaN
5                NaN
6                NaN
8                NaN
..               ...
105              Lee
106          L'Engle
107            Twain
108            Seuss
109           Martin

[110 rows x 5 columns]